<a href="https://colab.research.google.com/github/jinunyachhyon/Deep-Learning---PyTorch/blob/main/Initializing%20Tensors%2C%20Math%2C%20Indexing%2C%20Reshaping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import torch

# Initializing a Tensor

In [18]:
# Initializing Tensor
my_tensor = torch.tensor([[1,2,3], [4,5,6]], dtype=torch.float32)
my_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [19]:
# Other initialization methods
x = torch.empty(size=(3,3))
x

tensor([[ 2.4309e-34,  0.0000e+00, -2.8027e+15],
        [ 7.2996e+33,  1.1646e+24,  4.5785e-41],
        [ 2.4322e-34,  0.0000e+00, -7.3870e+25]])

In [20]:
x = torch.zeros((3,3))
x

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [21]:
x = torch.rand((3,3))
x

tensor([[0.4402, 0.8217, 0.7763],
        [0.3547, 0.0346, 0.1128],
        [0.6139, 0.9607, 0.8929]])

In [22]:
x = torch.ones((3,3))
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [23]:
torch.eye(5,5) # Identity matrix

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [24]:
torch.arange(start=0, end=5, step=1) # A range of value from start to end that jumps with given steps

tensor([0, 1, 2, 3, 4])

In [25]:
torch.linspace(start=0.1, end=1, steps=10) # Start with 0.1 and end 1, with tensor having 10 values

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [26]:
# Normal Distributed values
torch.empty(size=(3,3)).normal_(mean=0, std=1)

tensor([[ 0.4851,  0.3327, -0.3987],
        [-0.5294,  0.9261, -1.5855],
        [-0.6095,  0.5565, -1.4226]])

In [27]:
# Uniform Distributed values
torch.empty(size=(3,3)).uniform_(0,1)

tensor([[0.9642, 0.0395, 0.1779],
        [0.5467, 0.5329, 0.6573],
        [0.6148, 0.7983, 0.2922]])

# Converting between Array to Tensors

In [28]:
import numpy as np
np_array = np.array([[1,2],[3,4],[5,6]])
print(np_array)

array_to_tensor = torch.from_numpy(np_array)
print(array_to_tensor)

[[1 2]
 [3 4]
 [5 6]]
tensor([[1, 2],
        [3, 4],
        [5, 6]])


In [29]:
# Back to array from tensor
back_to_array = array_to_tensor.numpy()
print(back_to_array)

[[1 2]
 [3 4]
 [5 6]]


# Tensor Math & Comparison Operations

In [30]:
x = torch.tensor([[1,2,3],[5,6,7]])
y = torch.tensor([[8,9,10],[11,12,13]])

In [32]:
# Addition
print(torch.add(x,y))
print(x+y)

tensor([[ 9, 11, 13],
        [16, 18, 20]])
tensor([[ 9, 11, 13],
        [16, 18, 20]])


In [33]:
# Subtraction
x-y

tensor([[-7, -7, -7],
        [-6, -6, -6]])

In [36]:
# Division
print(x/y)
print(torch.true_divide(x,y))

tensor([[0.1250, 0.2222, 0.3000],
        [0.4545, 0.5000, 0.5385]])
tensor([[0.1250, 0.2222, 0.3000],
        [0.4545, 0.5000, 0.5385]])


In [40]:
# Multiplication (Element-wise)
x * y

tensor([[ 8, 18, 30],
        [55, 72, 91]])

In [43]:
# Dot product
torch.dot(torch.tensor([1,2]),torch.tensor([3,4]))

tensor(11)

In [37]:
# Inplace operation (using underscore _)
t = torch.zeros((2,3))
t.add_(x) # t = t+x

tensor([[1., 2., 3.],
        [5., 6., 7.]])

## Mathematics in Matrix

In [38]:
# Matrix Multiplication
x1 = torch.rand((2,5))
x2 = torch.rand((5,3))

torch.mm(x1, x2) # Output: 2x3

tensor([[2.0499, 2.1251, 1.1744],
        [1.9544, 1.6166, 0.7315]])

In [39]:
# Matrix Exponential 
matrix_exp = torch.rand(5,5)
matrix_exp.matrix_power(3)

tensor([[2.4397, 3.4638, 2.8358, 2.6230, 2.5329],
        [0.6314, 0.9388, 0.7470, 0.6896, 0.6754],
        [0.7430, 1.1602, 0.8915, 0.8608, 0.7525],
        [1.6575, 2.4752, 1.9314, 1.9064, 1.6744],
        [1.5045, 2.4136, 1.7250, 1.8399, 1.6108]])

In [44]:
# Batch Matrix Multiplication
batch = 32
n =10
m =20
p =30

tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out = torch.bmm(tensor1, tensor2)

print(out)
print(out.shape)

tensor([[[4.9903, 3.3348, 3.9685,  ..., 5.0077, 3.4592, 5.7276],
         [5.2105, 3.1722, 3.3587,  ..., 4.3623, 3.4300, 5.0585],
         [5.4026, 5.1604, 4.1888,  ..., 5.9809, 4.2747, 6.4499],
         ...,
         [5.6785, 3.8833, 3.5336,  ..., 4.7485, 4.3039, 6.0210],
         [4.5713, 3.6091, 3.6271,  ..., 4.8249, 3.1889, 5.1200],
         [3.9078, 2.7267, 2.4556,  ..., 3.8063, 2.7163, 4.1327]],

        [[4.8107, 5.0009, 4.4901,  ..., 5.8293, 6.2907, 4.2899],
         [4.7636, 4.5834, 4.7004,  ..., 6.5569, 5.7826, 4.9547],
         [3.4673, 4.6261, 4.0542,  ..., 4.8149, 5.2270, 4.3285],
         ...,
         [3.7489, 4.4672, 4.2567,  ..., 4.0492, 4.5682, 3.6756],
         [3.9976, 5.1025, 5.1202,  ..., 5.4569, 5.7278, 5.3895],
         [2.5476, 4.0606, 3.5223,  ..., 4.0300, 4.7444, 3.8537]],

        [[5.8576, 4.9577, 4.7361,  ..., 6.2609, 5.1008, 6.8773],
         [4.1361, 3.2310, 3.5119,  ..., 3.7873, 2.7118, 4.5836],
         [4.9658, 5.7927, 5.0784,  ..., 5.3420, 4.2976, 6.

In [52]:
# Operation within the matrix
x = torch.tensor([[[1,2,3],[4,5,6]],
                  [[2,4,6],[1,3,5]],
                  [[1,1,1],[2,2,2]]])

print(x)

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[2, 4, 6],
         [1, 3, 5]],

        [[1, 1, 1],
         [2, 2, 2]]])


In [53]:
torch.sum(x, dim=0)

tensor([[ 4,  7, 10],
        [ 7, 10, 13]])

In [54]:
torch.sum(x, dim=1)

tensor([[ 5,  7,  9],
        [ 3,  7, 11],
        [ 3,  3,  3]])

In [55]:
torch.sum(x, dim=2)

tensor([[ 6, 15],
        [12,  9],
        [ 3,  6]])

# Tensor Indexing

In [56]:
batch_size =10
features = 25

x = torch.rand((batch_size, features))

x[2, 0:10] # 3rd batch and its 10 features from 0 index to 9

tensor([0.6904, 0.9629, 0.5070, 0.7572, 0.1192, 0.0517, 0.9076, 0.6980, 0.8497,
        0.8849])

# Tensor Reshaping

In [57]:
x = torch.arange(9)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [58]:
x.view(3,3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [59]:
x.reshape(3,3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

**Note:** `reshape()` can operate on both contiguous and non-contiguous tensor while `view()` can only operate on contiguous tensor. 

Link to understand Contiguous Vs. Non-Contiguous: 
https://stackoverflow.com/questions/26998223/what-is-the-difference-between-contiguous-and-non-contiguous-arrays/26999092#26999092